// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: fintech/ledger/v1/ledger.proto

package ledgerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// JournalEntry is one leg of a balanced double-entry transaction.
//
// Sign convention: negative = debit, positive = credit. The signs of
// every leg in a transaction MUST sum to zero — enforced both in the
// service (domain.AssertBalanced) and in PostgreSQL.
type JournalEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// UUID of the entry (server-generated).
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// UUID of the owning transaction.
	TransactionId string `protobuf:"bytes,2,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	// UUID of the account this leg books against.
	AccountId string `protobuf:"bytes,3,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	// Decimal as string. The DB column is NUMERIC(19,4); JSON / proto
	// string preserves precision across language boundaries. Parsers
	// MUST use an arbitrary-precision decimal type.
	Amount string `protobuf:"bytes,4,opt,name=amount,proto3" json:"amount,omitempty"`
	// ISO-4217 alphabetic code, e.g. "USD", "EUR", "VND".
	Currency      string                 `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JournalEntry) Reset() {
	*x = JournalEntry{}
	mi := &file_fintech_ledger_v1_ledger_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JournalEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JournalEntry) ProtoMessage() {}

func (x *JournalEntry) ProtoReflect() protoreflect.Message {
	mi := &file_fintech_ledger_v1_ledger_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JournalEntry.ProtoReflect.Descriptor instead.
func (*JournalEntry) Descriptor() ([]byte, []int) {
	return file_fintech_ledger_v1_ledger_proto_rawDescGZIP(), []int{0}
}

func (x *JournalEntry) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *JournalEntry) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *JournalEntry) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *JournalEntry) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *JournalEntry) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *JournalEntry) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// Transaction is the aggregate that owns a balanced set of JournalEntry legs.
type Transaction struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,2,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	// Server-side state. Currently {COMMITTED, REVERSED}.
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Entries       []*JournalEntry        `protobuf:"bytes,4,rep,name=entries,proto3" json:"entries,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_fintech_ledger_v1_ledger_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_fintech_ledger_v1_ledger_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_fintech_ledger_v1_ledger_proto_rawDescGZIP(), []int{1}
}

func (x *Transaction) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Transaction) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *Transaction) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Transaction) GetEntries() []*JournalEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *Transaction) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// TransferRequest is the input to LedgerService.Transfer.
//
// Server generates the transaction id and journal-entry ids. The amount
// is signed POSITIVE — the server constructs the debit (-amount) and
// credit (+amount) legs internally.
type TransferRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Caller-supplied; uniquely identifies this transfer for at-most-once
	// semantics. Replays of the same key return the original transaction.
	IdempotencyKey string `protobuf:"bytes,1,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	// UUID of the account being debited.
	FromAccountId string `protobuf:"bytes,2,opt,name=from_account_id,json=fromAccountId,proto3" json:"from_account_id,omitempty"`
	// UUID of the account being credited.
	ToAccountId string `protobuf:"bytes,3,opt,name=to_account_id,json=toAccountId,proto3" json:"to_account_id,omitempty"`
	// Decimal-as-string. MUST be strictly positive.
	Amount        string `protobuf:"bytes,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency      string `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferRequest) Reset() {
	*x = TransferRequest{}
	mi := &file_fintech_ledger_v1_ledger_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferRequest) ProtoMessage() {}

func (x *TransferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fintech_ledger_v1_ledger_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferRequest.ProtoReflect.Descriptor instead.
func (*TransferRequest) Descriptor() ([]byte, []int) {
	return file_fintech_ledger_v1_ledger_proto_rawDescGZIP(), []int{2}
}

func (x *TransferRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *TransferRequest) GetFromAccountId() string {
	if x != nil {
		return x.FromAccountId
	}
	return ""
}

func (x *TransferRequest) GetToAccountId() string {
	if x != nil {
		return x.ToAccountId
	}
	return ""
}

func (x *TransferRequest) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *TransferRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type TransferResponse struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Transaction *Transaction           `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	// True when this response was reconstructed from a prior request under
	// the same idempotency_key. The Transaction is the original; no new
	// ledger row was written.
	Replayed      bool `protobuf:"varint,2,opt,name=replayed,proto3" json:"replayed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferResponse) Reset() {
	*x = TransferResponse{}
	mi := &file_fintech_ledger_v1_ledger_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferResponse) ProtoMessage() {}

func (x *TransferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fintech_ledger_v1_ledger_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferResponse.ProtoReflect.Descriptor instead.
func (*TransferResponse) Descriptor() ([]byte, []int) {
	return file_fintech_ledger_v1_ledger_proto_rawDescGZIP(), []int{3}
}

func (x *TransferResponse) GetTransaction() *Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

func (x *TransferResponse) GetReplayed() bool {
	if x != nil {
		return x.Replayed
	}
	return false
}

type GetTransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionRequest) Reset() {
	*x = GetTransactionRequest{}
	mi := &file_fintech_ledger_v1_ledger_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionRequest) ProtoMessage() {}

func (x *GetTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fintech_ledger_v1_ledger_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionRequest.ProtoReflect.Descriptor instead.
func (*GetTransactionRequest) Descriptor() ([]byte, []int) {
	return file_fintech_ledger_v1_ledger_proto_rawDescGZIP(), []int{4}
}

func (x *GetTransactionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetTransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transaction   *Transaction           `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionResponse) Reset() {
	*x = GetTransactionResponse{}
	mi := &file_fintech_ledger_v1_ledger_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionResponse) ProtoMessage() {}

func (x *GetTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fintech_ledger_v1_ledger_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionResponse.ProtoReflect.Descriptor instead.
func (*GetTransactionResponse) Descriptor() ([]byte, []int) {
	return file_fintech_ledger_v1_ledger_proto_rawDescGZIP(), []int{5}
}

func (x *GetTransactionResponse) GetTransaction() *Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

var File_fintech_ledger_v1_ledger_proto protoreflect.FileDescriptor

const file_fintech_ledger_v1_ledger_proto_rawDesc = "" +
	"\n" +
	"\x1efintech/ledger/v1/ledger.proto\x12\x11fintech.ledger.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd3\x01\n" +
	"\fJournalEntry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12%\n" +
	"\x0etransaction_id\x18\x02 \x01(\tR\rtransactionId\x12\x1d\n" +
	"\n" +
	"account_id\x18\x03 \x01(\tR\taccountId\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\tR\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xd4\x01\n" +
	"\vTransaction\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12'\n" +
	"\x0fidempotency_key\x18\x02 \x01(\tR\x0eidempotencyKey\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x129\n" +
	"\aentries\x18\x04 \x03(\v2\x1f.fintech.ledger.v1.JournalEntryR\aentries\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xba\x01\n" +
	"\x0fTransferRequest\x12'\n" +
	"\x0fidempotency_key\x18\x01 \x01(\tR\x0eidempotencyKey\x12&\n" +
	"\x0ffrom_account_id\x18\x02 \x01(\tR\rfromAccountId\x12\"\n" +
	"\rto_account_id\x18\x03 \x01(\tR\vtoAccountId\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\tR\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\"p\n" +
	"\x10TransferResponse\x12@\n" +
	"\vtransaction\x18\x01 \x01(\v2\x1e.fintech.ledger.v1.TransactionR\vtransaction\x12\x1a\n" +
	"\breplayed\x18\x02 \x01(\bR\breplayed\"'\n" +
	"\x15GetTransactionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"Z\n" +
	"\x16GetTransactionResponse\x12@\n" +
	"\vtransaction\x18\x01 \x01(\v2\x1e.fintech.ledger.v1.TransactionR\vtransaction2\xcb\x01\n" +
	"\rLedgerService\x12S\n" +
	"\bTransfer\x12\".fintech.ledger.v1.TransferRequest\x1a#.fintech.ledger.v1.TransferResponse\x12e\n" +
	"\x0eGetTransaction\x12(.fintech.ledger.v1.GetTransactionRequest\x1a).fintech.ledger.v1.GetTransactionResponseB\xd7\x01\n" +
	"\x15com.fintech.ledger.v1B\vLedgerProtoP\x01ZKgithub.com/phuongdpham/fintech/libs/go/proto-gen/fintech/ledger/v1;ledgerv1\xa2\x02\x03FLX\xaa\x02\x11Fintech.Ledger.V1\xca\x02\x11Fintech\\Ledger\\V1\xe2\x02\x1dFintech\\Ledger\\V1\\GPBMetadata\xea\x02\x13Fintech::Ledger::V1b\x06proto3"

var (
	file_fintech_ledger_v1_ledger_proto_rawDescOnce sync.Once
	file_fintech_ledger_v1_ledger_proto_rawDescData []byte
)

func file_fintech_ledger_v1_ledger_proto_rawDescGZIP() []byte {
	file_fintech_ledger_v1_ledger_proto_rawDescOnce.Do(func() {
		file_fintech_ledger_v1_ledger_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fintech_ledger_v1_ledger_proto_rawDesc), len(file_fintech_ledger_v1_ledger_proto_rawDesc)))
	})
	return file_fintech_ledger_v1_ledger_proto_rawDescData
}

var file_fintech_ledger_v1_ledger_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_fintech_ledger_v1_ledger_proto_goTypes = []any{
	(*JournalEntry)(nil),           // 0: fintech.ledger.v1.JournalEntry
	(*Transaction)(nil),            // 1: fintech.ledger.v1.Transaction
	(*TransferRequest)(nil),        // 2: fintech.ledger.v1.TransferRequest
	(*TransferResponse)(nil),       // 3: fintech.ledger.v1.TransferResponse
	(*GetTransactionRequest)(nil),  // 4: fintech.ledger.v1.GetTransactionRequest
	(*GetTransactionResponse)(nil), // 5: fintech.ledger.v1.GetTransactionResponse
	(*timestamppb.Timestamp)(nil),  // 6: google.protobuf.Timestamp
}
var file_fintech_ledger_v1_ledger_proto_depIdxs = []int32{
	6, // 0: fintech.ledger.v1.JournalEntry.created_at:type_name -> google.protobuf.Timestamp
	0, // 1: fintech.ledger.v1.Transaction.entries:type_name -> fintech.ledger.v1.JournalEntry
	6, // 2: fintech.ledger.v1.Transaction.created_at:type_name -> google.protobuf.Timestamp
	1, // 3: fintech.ledger.v1.TransferResponse.transaction:type_name -> fintech.ledger.v1.Transaction
	1, // 4: fintech.ledger.v1.GetTransactionResponse.transaction:type_name -> fintech.ledger.v1.Transaction
	2, // 5: fintech.ledger.v1.LedgerService.Transfer:input_type -> fintech.ledger.v1.TransferRequest
	4, // 6: fintech.ledger.v1.LedgerService.GetTransaction:input_type -> fintech.ledger.v1.GetTransactionRequest
	3, // 7: fintech.ledger.v1.LedgerService.Transfer:output_type -> fintech.ledger.v1.TransferResponse
	5, // 8: fintech.ledger.v1.LedgerService.GetTransaction:output_type -> fintech.ledger.v1.GetTransactionResponse
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_fintech_ledger_v1_ledger_proto_init() }
func file_fintech_ledger_v1_ledger_proto_init() {
	if File_fintech_ledger_v1_ledger_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fintech_ledger_v1_ledger_proto_rawDesc), len(file_fintech_ledger_v1_ledger_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_fintech_ledger_v1_ledger_proto_goTypes,
		DependencyIndexes: file_fintech_ledger_v1_ledger_proto_depIdxs,
		MessageInfos:      file_fintech_ledger_v1_ledger_proto_msgTypes,
	}.Build()
	File_fintech_ledger_v1_ledger_proto = out.File
	file_fintech_ledger_v1_ledger_proto_goTypes = nil
	file_fintech_ledger_v1_ledger_proto_depIdxs = nil
}
