// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go
//
// Generated by this command:
//
//	mockgen -source=repository.go -destination=mocks/mock_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	domain "github.com/phuongdpham/fintech/apps/ledger-svc/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockAccountRepository is a mock of AccountRepository interface.
type MockAccountRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAccountRepositoryMockRecorder
	isgomock struct{}
}

// MockAccountRepositoryMockRecorder is the mock recorder for MockAccountRepository.
type MockAccountRepositoryMockRecorder struct {
	mock *MockAccountRepository
}

// NewMockAccountRepository creates a new mock instance.
func NewMockAccountRepository(ctrl *gomock.Controller) *MockAccountRepository {
	mock := &MockAccountRepository{ctrl: ctrl}
	mock.recorder = &MockAccountRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccountRepository) EXPECT() *MockAccountRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockAccountRepository) Create(ctx context.Context, a *domain.Account) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, a)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockAccountRepositoryMockRecorder) Create(ctx, a any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAccountRepository)(nil).Create), ctx, a)
}

// GetByID mocks base method.
func (m *MockAccountRepository) GetByID(ctx context.Context, id uuid.UUID) (*domain.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*domain.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockAccountRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockAccountRepository)(nil).GetByID), ctx, id)
}

// MockLedgerRepository is a mock of LedgerRepository interface.
type MockLedgerRepository struct {
	ctrl     *gomock.Controller
	recorder *MockLedgerRepositoryMockRecorder
	isgomock struct{}
}

// MockLedgerRepositoryMockRecorder is the mock recorder for MockLedgerRepository.
type MockLedgerRepositoryMockRecorder struct {
	mock *MockLedgerRepository
}

// NewMockLedgerRepository creates a new mock instance.
func NewMockLedgerRepository(ctrl *gomock.Controller) *MockLedgerRepository {
	mock := &MockLedgerRepository{ctrl: ctrl}
	mock.recorder = &MockLedgerRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLedgerRepository) EXPECT() *MockLedgerRepositoryMockRecorder {
	return m.recorder
}

// ExecuteTransfer mocks base method.
func (m *MockLedgerRepository) ExecuteTransfer(ctx context.Context, req domain.TransferRequest) (*domain.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecuteTransfer", ctx, req)
	ret0, _ := ret[0].(*domain.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExecuteTransfer indicates an expected call of ExecuteTransfer.
func (mr *MockLedgerRepositoryMockRecorder) ExecuteTransfer(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecuteTransfer", reflect.TypeOf((*MockLedgerRepository)(nil).ExecuteTransfer), ctx, req)
}

// GetTransaction mocks base method.
func (m *MockLedgerRepository) GetTransaction(ctx context.Context, id uuid.UUID) (*domain.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTransaction", ctx, id)
	ret0, _ := ret[0].(*domain.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTransaction indicates an expected call of GetTransaction.
func (mr *MockLedgerRepositoryMockRecorder) GetTransaction(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTransaction", reflect.TypeOf((*MockLedgerRepository)(nil).GetTransaction), ctx, id)
}

// GetTransactionByIdempotencyKey mocks base method.
func (m *MockLedgerRepository) GetTransactionByIdempotencyKey(ctx context.Context, tenantID, key string) (*domain.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTransactionByIdempotencyKey", ctx, tenantID, key)
	ret0, _ := ret[0].(*domain.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTransactionByIdempotencyKey indicates an expected call of GetTransactionByIdempotencyKey.
func (mr *MockLedgerRepositoryMockRecorder) GetTransactionByIdempotencyKey(ctx, tenantID, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTransactionByIdempotencyKey", reflect.TypeOf((*MockLedgerRepository)(nil).GetTransactionByIdempotencyKey), ctx, tenantID, key)
}

// MockOutboxRepository is a mock of OutboxRepository interface.
type MockOutboxRepository struct {
	ctrl     *gomock.Controller
	recorder *MockOutboxRepositoryMockRecorder
	isgomock struct{}
}

// MockOutboxRepositoryMockRecorder is the mock recorder for MockOutboxRepository.
type MockOutboxRepositoryMockRecorder struct {
	mock *MockOutboxRepository
}

// NewMockOutboxRepository creates a new mock instance.
func NewMockOutboxRepository(ctrl *gomock.Controller) *MockOutboxRepository {
	mock := &MockOutboxRepository{ctrl: ctrl}
	mock.recorder = &MockOutboxRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOutboxRepository) EXPECT() *MockOutboxRepositoryMockRecorder {
	return m.recorder
}

// MarkPublished mocks base method.
func (m *MockOutboxRepository) MarkPublished(ctx context.Context, ids []uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkPublished", ctx, ids)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkPublished indicates an expected call of MarkPublished.
func (mr *MockOutboxRepositoryMockRecorder) MarkPublished(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkPublished", reflect.TypeOf((*MockOutboxRepository)(nil).MarkPublished), ctx, ids)
}

// SelectPending mocks base method.
func (m *MockOutboxRepository) SelectPending(ctx context.Context, limit int) ([]*domain.OutboxEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectPending", ctx, limit)
	ret0, _ := ret[0].([]*domain.OutboxEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectPending indicates an expected call of SelectPending.
func (mr *MockOutboxRepositoryMockRecorder) SelectPending(ctx, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectPending", reflect.TypeOf((*MockOutboxRepository)(nil).SelectPending), ctx, limit)
}

// MockIdempotencyStore is a mock of IdempotencyStore interface.
type MockIdempotencyStore struct {
	ctrl     *gomock.Controller
	recorder *MockIdempotencyStoreMockRecorder
	isgomock struct{}
}

// MockIdempotencyStoreMockRecorder is the mock recorder for MockIdempotencyStore.
type MockIdempotencyStoreMockRecorder struct {
	mock *MockIdempotencyStore
}

// NewMockIdempotencyStore creates a new mock instance.
func NewMockIdempotencyStore(ctrl *gomock.Controller) *MockIdempotencyStore {
	mock := &MockIdempotencyStore{ctrl: ctrl}
	mock.recorder = &MockIdempotencyStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIdempotencyStore) EXPECT() *MockIdempotencyStoreMockRecorder {
	return m.recorder
}

// Acquire mocks base method.
func (m *MockIdempotencyStore) Acquire(ctx context.Context, key, fingerprint string) (bool, domain.IdempotencyRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Acquire", ctx, key, fingerprint)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(domain.IdempotencyRecord)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Acquire indicates an expected call of Acquire.
func (mr *MockIdempotencyStoreMockRecorder) Acquire(ctx, key, fingerprint any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Acquire", reflect.TypeOf((*MockIdempotencyStore)(nil).Acquire), ctx, key, fingerprint)
}

// SetState mocks base method.
func (m *MockIdempotencyStore) SetState(ctx context.Context, key, fingerprint string, state domain.IdempotencyState) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetState", ctx, key, fingerprint, state)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetState indicates an expected call of SetState.
func (mr *MockIdempotencyStoreMockRecorder) SetState(ctx, key, fingerprint, state any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetState", reflect.TypeOf((*MockIdempotencyStore)(nil).SetState), ctx, key, fingerprint, state)
}
